artifact_uri: s3://sars-cov-2-25309b4013524/2/2e7de1e246734eb6ad75ed4fec59a3cd/artifacts
end_time: 1590094761315
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 2e7de1e246734eb6ad75ed4fec59a3cd
run_uuid: 2e7de1e246734eb6ad75ed4fec59a3cd
source_name: ''
source_type: 4
source_version: ''
start_time: 1590094661619
status: 3
tags: []
user_id: ''
