artifact_uri: s3://sars-cov-2-25309b4013524/2/6ad5a7f302cd41bb9ee5b5cac0de648a/artifacts
end_time: 1590094119402
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 6ad5a7f302cd41bb9ee5b5cac0de648a
run_uuid: 6ad5a7f302cd41bb9ee5b5cac0de648a
source_name: ''
source_type: 4
source_version: ''
start_time: 1590094025451
status: 3
tags: []
user_id: ''
